version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: ./container/frontend/Dockerfile
    ports:
      - 3000:3000

  server:
    build:
      context: .
      dockerfile: ./container/backend/Dockerfile
    volumes:
      - ./backend/:/backend/
    env_file:
      - ./backend/.env
    ports:
      - 9191:9191
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env
    ports:
      - 5432:5432 #https://docs.docker.com/compose/networking/
  
  redis:
    image: redis:6.2-alpine

  celery_worker:
    build:
      context: .
      dockerfile: ./container/celery/Dockerfile
    volumes:
      - ./backend/:/backend/
    env_file:
      - ./backend/.env
    depends_on:
      - server
      - redis

  flower:
    build:
      context: .
      dockerfile: ./container/flower/Dockerfile
    ports:
      - 5556:5555
    env_file:
      - ./backend/.env
    depends_on:
      - server
      - redis
      - celery_worker

volumes:
    postgres_data: