name: Docker Image CI

on: [push]

jobs:

  build-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Github Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.ACTIONS_PAT }}
        
    - name: Build the Docker image
      run: |
        docker build . --file ./backend/Dockerfile --tag ghcr.io/stevoabr/bearwatch:latest
        docker run gchcr.io/stevoabr/bearwatch:latest
        docker push ghcr.io/stevoabr/bearwatch:latest
  
  build-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file ./backend/Dockerfile --tag bearwatch:$(date +%s)
